#+title:Leet
--------------------------------------
leetcode question and solution samples

* Philosophy:
This repository stores my answers to some random leetcode questions. I generally have the best solution with mine at files. Also sometimes I am just givving up and not finnishing the algorithm. (I am trying to include //NOT WORKING like first-line comments to indicate that) So feel free to create a pull request and merge it to the repository or wait for it till I fix it (If I do)

* Thoughts:
Mainly Rust? I think I might taste a bit of algorithms juice

* Trying:
To try anything in this repository you will use (if I don't change it after) =rustc= which is the rust compiler that allows you to compile manually (normally rustc is managed by [[https://en.wikipedia.org/wiki/Rust_(programming_language)][rust]] package manager called [[https://en.wikipedia.org/wiki/Rust_(programming_language)][cargo]] automatically)
It works pretty much same as [[https://gcc.gnu.org/][GNU Compiler Collection]] (C/C++ compiler) but it is for rust.

You just need to do:
=rustc <filename>.rs; ./<filename>=

to be able to compile and run the file. (unlike gcc it compiles directly to the filename instead of ~a.out~ which is good)

* LICENSE:
#+begin_src text
Copyright 2023 KoBruhh

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#+end_src
